name: Deploy iOS

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:
    inputs:
      upload_to_testflight:
        description: "Deploy to Apple TestFlight"
        required: false
        default: true
        type: boolean

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    uses: exa31/github-workflows/.github/workflows/flutter-ios.yml@main
    with:
      app_name: f-tracker-mobile
      flutter_version: "3.x"
      enable_semantic_release: false
      update_pubspec: false
      upload_to_testflight: ${{ github.event_name == 'workflow_run' || inputs.upload_to_testflight == true }}
    secrets:
      ENV_FILE: ${{ secrets.ENV_FILE }}
      APPLE_CERTIFICATE_BASE64: ${{ secrets.APPLE_CERTIFICATE_BASE64 }}
      APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
      APPLE_PROVISIONING_PROFILE_BASE64: ${{ secrets.APPLE_PROVISIONING_PROFILE_BASE64 }}
      APP_STORE_CONNECT_API_KEY_BASE64: ${{ secrets.APP_STORE_CONNECT_API_KEY_BASE64 }}
      APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
      APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
